allow_cancel_vote: true
hide_vote_widget: false
enabled_types:
  comment:
    - comment
    - post_comment
  node:
    - topic
    - event
  post:
    - post
_core:
  default_config_hash: v8zOJVZLS-en7NcVdxnPvhRbnakYqCV9dd1eTRtPf-g
delete_everywhere: false
