social_profile_show_email: true
social_profile_show_language: true
enable_profile_tagging: true
allow_category_split: false
use_category_parent: false
allow_tagging_for_lu: false
_core:
  default_config_hash: TXDIaLMTN_2p2ubK_fNjf1bkJ8mTi8XYvpiMV2EJPFE
