favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://dev-opensocial-drops-9-test.pantheonsite.io/themes/contrib/socialbase/favicon.ico'
  use_default: true
schema: '8000'
features:
  comment_user_picture: true
  comment_user_verification: false
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
region_wells:
  breadcrumb: ''
  hero: ''
  primary_action: ''
  secondary_navigation: ''
  complementary: ''
forms_smart_descriptions: false
cdn_provider: ''
popover_trigger: hover
tooltip_enabled: false
button_colorize: false
button_iconize: false
modal_enabled: false
_core:
  default_config_hash: Ns05eL8VLQDyIA-VFS4S72lFmUtbyM0gaOIgbrRlGuA
schemas:
  bootstrap: 8000
  socialbase: 8000
